#!/bin/bash
# GENERATED BY GITHUB COPILOT
# Deployment script for GameVault Tracker Azure Infrastructure
# This script automates the deployment of all Azure resources using Bicep

set -e

# GENERATED BY GITHUB COPILOT - Script configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_ROOT="$(dirname "$INFRA_DIR")"

# GENERATED BY GITHUB COPILOT - Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# GENERATED BY GITHUB COPILOT - Helper functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# GENERATED BY GITHUB COPILOT - Display usage information
usage() {
    cat << EOF
Usage: $0 [OPTIONS]

Deploy GameVault Tracker infrastructure to Azure

OPTIONS:
    -e, --environment ENV      Environment name (dev, test, prod) [required]
    -g, --resource-group RG    Resource group name [required]
    -l, --location LOC         Azure location (default: eastus)
    -s, --subscription SUB     Azure subscription ID (optional)
    -t, --token TOKEN          GitHub Personal Access Token (optional)
    -w, --what-if              Perform what-if analysis only (no deployment)
    -v, --validate             Validate template only (no deployment)
    -h, --help                 Show this help message

EXAMPLES:
    # Deploy development environment
    $0 --environment dev --resource-group rg-gamevault-dev

    # Deploy with specific subscription
    $0 -e prod -g rg-gamevault-prod -s xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

    # Perform what-if analysis
    $0 -e dev -g rg-gamevault-dev --what-if

    # Validate template
    $0 -e dev -g rg-gamevault-dev --validate

EOF
    exit 1
}

# GENERATED BY GITHUB COPILOT - Parse command line arguments
ENVIRONMENT=""
RESOURCE_GROUP=""
LOCATION="eastus"
SUBSCRIPTION=""
GITHUB_TOKEN=""
WHAT_IF=false
VALIDATE=false

while [[ $# -gt 0 ]]; do
    case $1 in
        -e|--environment)
            ENVIRONMENT="$2"
            shift 2
            ;;
        -g|--resource-group)
            RESOURCE_GROUP="$2"
            shift 2
            ;;
        -l|--location)
            LOCATION="$2"
            shift 2
            ;;
        -s|--subscription)
            SUBSCRIPTION="$2"
            shift 2
            ;;
        -t|--token)
            GITHUB_TOKEN="$2"
            shift 2
            ;;
        -w|--what-if)
            WHAT_IF=true
            shift
            ;;
        -v|--validate)
            VALIDATE=true
            shift
            ;;
        -h|--help)
            usage
            ;;
        *)
            log_error "Unknown option: $1"
            usage
            ;;
    esac
done

# GENERATED BY GITHUB COPILOT - Validate required parameters
if [[ -z "$ENVIRONMENT" ]]; then
    log_error "Environment is required"
    usage
fi

if [[ -z "$RESOURCE_GROUP" ]]; then
    log_error "Resource group is required"
    usage
fi

# GENERATED BY GITHUB COPILOT - Validate environment name
if [[ ! "$ENVIRONMENT" =~ ^(dev|test|staging|prod)$ ]]; then
    log_error "Environment must be one of: dev, test, staging, prod"
    exit 1
fi

# GENERATED BY GITHUB COPILOT - Check prerequisites
log_info "Checking prerequisites..."

if ! command -v az &> /dev/null; then
    log_error "Azure CLI is not installed. Please install it from: https://docs.microsoft.com/cli/azure/install-azure-cli"
    exit 1
fi

log_success "Azure CLI found: $(az version --query '"azure-cli"' -o tsv)"

# GENERATED BY GITHUB COPILOT - Check Azure login
log_info "Checking Azure login status..."
if ! az account show &> /dev/null; then
    log_error "Not logged in to Azure. Please run: az login"
    exit 1
fi

CURRENT_ACCOUNT=$(az account show --query "name" -o tsv)
log_success "Logged in to Azure as: $CURRENT_ACCOUNT"

# GENERATED BY GITHUB COPILOT - Set subscription if provided
if [[ -n "$SUBSCRIPTION" ]]; then
    log_info "Setting subscription to: $SUBSCRIPTION"
    az account set --subscription "$SUBSCRIPTION"
fi

CURRENT_SUBSCRIPTION=$(az account show --query "id" -o tsv)
log_info "Using subscription: $CURRENT_SUBSCRIPTION"

# GENERATED BY GITHUB COPILOT - Create resource group if it doesn't exist
log_info "Checking resource group: $RESOURCE_GROUP"
if ! az group show --name "$RESOURCE_GROUP" &> /dev/null; then
    log_info "Resource group does not exist. Creating..."
    az group create --name "$RESOURCE_GROUP" --location "$LOCATION" --tags Environment="$ENVIRONMENT" ManagedBy="Bicep"
    log_success "Resource group created: $RESOURCE_GROUP"
else
    log_success "Resource group exists: $RESOURCE_GROUP"
fi

# GENERATED BY GITHUB COPILOT - Prepare deployment parameters
PARAMETERS_FILE="$INFRA_DIR/parameters.${ENVIRONMENT}.json"

if [[ ! -f "$PARAMETERS_FILE" ]]; then
    log_error "Parameters file not found: $PARAMETERS_FILE"
    exit 1
fi

log_info "Using parameters file: $PARAMETERS_FILE"

# GENERATED BY GITHUB COPILOT - Build parameter overrides
PARAM_OVERRIDES="location=$LOCATION"

if [[ -n "$GITHUB_TOKEN" ]]; then
    PARAM_OVERRIDES="$PARAM_OVERRIDES repositoryToken=$GITHUB_TOKEN"
    log_info "GitHub token provided for Static Web App deployment"
else
    log_warning "GitHub token not provided. Static Web App will not be configured for CI/CD"
    PARAM_OVERRIDES="$PARAM_OVERRIDES repositoryToken=''"
fi

# GENERATED BY GITHUB COPILOT - Generate deployment name
DEPLOYMENT_NAME="gamevault-${ENVIRONMENT}-$(date +%Y%m%d-%H%M%S)"

# GENERATED BY GITHUB COPILOT - Validate template
if [[ "$VALIDATE" == true ]]; then
    log_info "Validating Bicep template..."
    az deployment group validate \
        --resource-group "$RESOURCE_GROUP" \
        --template-file "$INFRA_DIR/main.bicep" \
        --parameters "@$PARAMETERS_FILE" \
        --parameters $PARAM_OVERRIDES \
        --name "$DEPLOYMENT_NAME"
    
    log_success "Template validation completed successfully"
    exit 0
fi

# GENERATED BY GITHUB COPILOT - What-if analysis
if [[ "$WHAT_IF" == true ]]; then
    log_info "Running what-if analysis..."
    az deployment group what-if \
        --resource-group "$RESOURCE_GROUP" \
        --template-file "$INFRA_DIR/main.bicep" \
        --parameters "@$PARAMETERS_FILE" \
        --parameters $PARAM_OVERRIDES \
        --name "$DEPLOYMENT_NAME"
    
    log_success "What-if analysis completed"
    exit 0
fi

# GENERATED BY GITHUB COPILOT - Deploy infrastructure
log_info "Starting deployment: $DEPLOYMENT_NAME"
log_info "Environment: $ENVIRONMENT"
log_info "Resource Group: $RESOURCE_GROUP"
log_info "Location: $LOCATION"

az deployment group create \
    --resource-group "$RESOURCE_GROUP" \
    --template-file "$INFRA_DIR/main.bicep" \
    --parameters "@$PARAMETERS_FILE" \
    --parameters $PARAM_OVERRIDES \
    --name "$DEPLOYMENT_NAME" \
    --output json > "$INFRA_DIR/deployment-output.json"

# GENERATED BY GITHUB COPILOT - Check deployment result
if [[ $? -eq 0 ]]; then
    log_success "Deployment completed successfully!"
    
    # GENERATED BY GITHUB COPILOT - Extract and display outputs
    log_info "Extracting deployment outputs..."
    
    STORAGE_ACCOUNT=$(jq -r '.properties.outputs.storageAccountName.value' "$INFRA_DIR/deployment-output.json")
    STATIC_WEB_APP=$(jq -r '.properties.outputs.staticWebAppName.value' "$INFRA_DIR/deployment-output.json")
    APP_URL=$(jq -r '.properties.outputs.staticWebAppUrl.value' "$INFRA_DIR/deployment-output.json")
    
    echo ""
    log_success "=== DEPLOYMENT SUMMARY ==="
    echo "Environment:       $ENVIRONMENT"
    echo "Resource Group:    $RESOURCE_GROUP"
    echo "Storage Account:   $STORAGE_ACCOUNT"
    echo "Static Web App:    $STATIC_WEB_APP"
    echo "Application URL:   https://$APP_URL"
    echo ""
    
    log_info "Next steps:"
    echo "1. Update CORS settings to include: https://$APP_URL"
    echo "2. Configure GitHub Secrets for CI/CD:"
    echo "   - AZURE_STATIC_WEB_APPS_API_TOKEN"
    echo "   - VITE_AZURE_STORAGE_ACCOUNT_NAME=$STORAGE_ACCOUNT"
    echo "   - VITE_AZURE_STORAGE_SAS_TOKEN (from deployment outputs)"
    echo "3. Push code to trigger GitHub Actions deployment"
    echo ""
    log_info "To update CORS, run:"
    echo "   $SCRIPT_DIR/update-cors.sh -g $RESOURCE_GROUP -s $STORAGE_ACCOUNT -o https://$APP_URL"
    echo ""
    
    # GENERATED BY GITHUB COPILOT - Save environment configuration
    ENV_CONFIG_FILE="$INFRA_DIR/.env.$ENVIRONMENT"
    jq -r '.properties.outputs.environmentConfig.value | to_entries | .[] | "\(.key)=\(.value)"' \
        "$INFRA_DIR/deployment-output.json" > "$ENV_CONFIG_FILE"
    
    log_success "Environment configuration saved to: $ENV_CONFIG_FILE"
    log_warning "IMPORTANT: This file contains sensitive information. Do not commit it to version control!"
    
else
    log_error "Deployment failed!"
    exit 1
fi
