#!/bin/bash
# GENERATED BY GITHUB COPILOT
# Teardown script for GameVault Tracker Azure Infrastructure
# Removes all Azure resources for an environment

set -e

# GENERATED BY GITHUB COPILOT - Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# GENERATED BY GITHUB COPILOT - Helper functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# GENERATED BY GITHUB COPILOT - Display usage information
usage() {
    cat << EOF
Usage: $0 [OPTIONS]

Teardown GameVault Tracker infrastructure from Azure

OPTIONS:
    -g, --resource-group RG    Resource group name [required]
    -f, --force                Skip confirmation prompt
    -k, --keep-data            Keep storage account data (only remove other resources)
    -h, --help                 Show this help message

EXAMPLES:
    # Teardown with confirmation
    $0 --resource-group rg-gamevault-dev

    # Force teardown without confirmation
    $0 -g rg-gamevault-dev --force

    # Remove resources but keep data
    $0 -g rg-gamevault-dev --keep-data

EOF
    exit 1
}

# GENERATED BY GITHUB COPILOT - Parse command line arguments
RESOURCE_GROUP=""
FORCE=false
KEEP_DATA=false

while [[ $# -gt 0 ]]; do
    case $1 in
        -g|--resource-group)
            RESOURCE_GROUP="$2"
            shift 2
            ;;
        -f|--force)
            FORCE=true
            shift
            ;;
        -k|--keep-data)
            KEEP_DATA=true
            shift
            ;;
        -h|--help)
            usage
            ;;
        *)
            log_error "Unknown option: $1"
            usage
            ;;
    esac
done

# GENERATED BY GITHUB COPILOT - Validate required parameters
if [[ -z "$RESOURCE_GROUP" ]]; then
    log_error "Resource group is required"
    usage
fi

# GENERATED BY GITHUB COPILOT - Check prerequisites
if ! command -v az &> /dev/null; then
    log_error "Azure CLI is not installed"
    exit 1
fi

# GENERATED BY GITHUB COPILOT - Check Azure login
if ! az account show &> /dev/null; then
    log_error "Not logged in to Azure. Please run: az login"
    exit 1
fi

# GENERATED BY GITHUB COPILOT - Verify resource group exists
log_info "Checking resource group: $RESOURCE_GROUP"
if ! az group show --name "$RESOURCE_GROUP" &> /dev/null; then
    log_error "Resource group not found: $RESOURCE_GROUP"
    exit 1
fi

# GENERATED BY GITHUB COPILOT - List resources
log_info "Resources in $RESOURCE_GROUP:"
az resource list --resource-group "$RESOURCE_GROUP" --output table

# GENERATED BY GITHUB COPILOT - Confirmation prompt
if [[ "$FORCE" == false ]]; then
    echo ""
    log_warning "This will DELETE all resources in the resource group: $RESOURCE_GROUP"
    if [[ "$KEEP_DATA" == true ]]; then
        log_info "Storage account data will be preserved"
    else
        log_warning "ALL DATA WILL BE PERMANENTLY DELETED"
    fi
    echo ""
    read -p "Are you sure you want to continue? (yes/no): " -r
    echo
    if [[ ! $REPLY =~ ^[Yy][Ee][Ss]$ ]]; then
        log_info "Teardown cancelled"
        exit 0
    fi
fi

# GENERATED BY GITHUB COPILOT - Perform teardown
if [[ "$KEEP_DATA" == true ]]; then
    log_warning "Keeping storage account data is not yet implemented"
    log_info "This will still delete the entire resource group"
fi

log_info "Deleting resource group: $RESOURCE_GROUP"
az group delete --name "$RESOURCE_GROUP" --yes --no-wait

log_success "Teardown initiated for: $RESOURCE_GROUP"
log_info "Deletion is running in the background"
log_info "To check status, run: az group show --name $RESOURCE_GROUP"
