#!/bin/bash
# GENERATED BY GITHUB COPILOT
# Script to update CORS settings for Azure Storage Account
# Allows adding origins dynamically after deployment

set -e

# GENERATED BY GITHUB COPILOT - Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# GENERATED BY GITHUB COPILOT - Helper functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# GENERATED BY GITHUB COPILOT - Display usage information
usage() {
    cat << EOF
Usage: $0 [OPTIONS]

Update CORS settings for Azure Storage Account

OPTIONS:
    -g, --resource-group RG    Resource group name [required]
    -s, --storage-account SA   Storage account name [required]
    -o, --origin ORIGIN        Origin to add (can be specified multiple times) [required]
    -h, --help                 Show this help message

EXAMPLES:
    # Add a single origin
    $0 -g rg-gamevault-dev -s stgamevaultdev123456 -o https://my-app.azurestaticapps.net

    # Add multiple origins
    $0 -g rg-gamevault-dev -s stgamevaultdev123456 -o https://app1.com -o https://app2.com

EOF
    exit 1
}

# GENERATED BY GITHUB COPILOT - Parse command line arguments
RESOURCE_GROUP=""
STORAGE_ACCOUNT=""
ORIGINS=()

while [[ $# -gt 0 ]]; do
    case $1 in
        -g|--resource-group)
            RESOURCE_GROUP="$2"
            shift 2
            ;;
        -s|--storage-account)
            STORAGE_ACCOUNT="$2"
            shift 2
            ;;
        -o|--origin)
            ORIGINS+=("$2")
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            log_error "Unknown option: $1"
            usage
            ;;
    esac
done

# GENERATED BY GITHUB COPILOT - Validate required parameters
if [[ -z "$RESOURCE_GROUP" ]]; then
    log_error "Resource group is required"
    usage
fi

if [[ -z "$STORAGE_ACCOUNT" ]]; then
    log_error "Storage account is required"
    usage
fi

if [[ ${#ORIGINS[@]} -eq 0 ]]; then
    log_error "At least one origin is required"
    usage
fi

# GENERATED BY GITHUB COPILOT - Check prerequisites
if ! command -v az &> /dev/null; then
    log_error "Azure CLI is not installed"
    exit 1
fi

# GENERATED BY GITHUB COPILOT - Verify storage account exists
log_info "Verifying storage account: $STORAGE_ACCOUNT"
if ! az storage account show --name "$STORAGE_ACCOUNT" --resource-group "$RESOURCE_GROUP" &> /dev/null; then
    log_error "Storage account not found: $STORAGE_ACCOUNT"
    exit 1
fi

# GENERATED BY GITHUB COPILOT - Add CORS rules for each origin
log_info "Adding CORS rules for Table Storage..."

for ORIGIN in "${ORIGINS[@]}"; do
    log_info "Adding origin: $ORIGIN"
    
    az storage cors add \
        --account-name "$STORAGE_ACCOUNT" \
        --services t \
        --methods GET POST PUT DELETE OPTIONS \
        --origins "$ORIGIN" \
        --allowed-headers "*" \
        --exposed-headers "*" \
        --max-age 3600
    
    log_success "Added CORS rule for: $ORIGIN"
done

log_success "CORS configuration updated successfully!"
log_info "Note: It may take a few minutes for CORS changes to propagate"
