#!/usr/bin/env bash
set -e

echo "📝 Creating .env.production file..."
cat > .env.production <<EOF
VITE_AZURE_STORAGE_ACCOUNT_NAME=$VITE_AZURE_STORAGE_ACCOUNT_NAME
VITE_AZURE_STORAGE_SAS_TOKEN=$VITE_AZURE_STORAGE_SAS_TOKEN
VITE_AZURE_GAMES_TABLE_NAME=$VITE_AZURE_GAMES_TABLE_NAME
VITE_AZURE_CATEGORIES_TABLE_NAME=$VITE_AZURE_CATEGORIES_TABLE_NAME
EOF
echo "✅ .env.production created"
