apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gamevault-tracker-azure-src
  description: The source code for the GameVault Tracker Azure application.
  annotations:
    github.com/project-slug: matteoemili/gamevault-tracker-azure
    backstage.io/techdocs-ref: dir:.
  tags:
    - react
    - azure
  links:
    - url: https://github.com/matteoemili/gamevault-tracker-azure
      title: Source Code
      icon: github
spec:
  type: website
  system: gamevault-tracker-azure # Optional: groups components together
  lifecycle: production # e.g., experimental, production, deprecated
  owner: acme # Links to a Group or User entity